const mongoose = require("mongoose");

const products = new mongoose.Schema({
  id: { type: Number },
  category: { type: String },
  imgUrl: { type: String },
  name: { type: String },
  display: { type: Number },
  color_0: { type: String },
  color_1: { type: String },
  color_2: { type: String },
  price: { type: Number },
  chip_name: { type: String },
  chip_cores: { type: Number },
  ram: { type: Number },
  storage: { type: Number },
  touchId: { type: Boolean },
  faceId: { type: Boolean },
  wireless_0: { type: String },
  wireless_1: { type: String },
  camera_front: { type: String },
  audio_microphone: { type: String },
  audio_speakers: { type: String },
  size_height: { type: String },
  size_width: { type: String },
  size_depth: { type: String },
  size_weight: { type: String },
  os: { type: String },
  InTheBox_0: { type: String },
  InTheBox_1: { type: String },
  InTheBox_2: { type: String },
  orderInfo_inStock: { type: Number },
  orderInfo_reviews: { type: Number },
  orderInfo_orders: { type: Number },
  InTheBox_3: { type: String },
  InTheBox_4: { type: String },
  InTheBox_5: { type: String },
  camera_back: { type: String },
  color_3: { type: String },
  color_4: { type: String },
  wireless_2: { type: String },
  color_5: { type: String },
});

module.exports = mongoose.model("products", products);